language: node_js
node_js:
- '12'
- '13'
script:
- echo 'Starting'
- npm install
- echo 'Testing'
- npm test
deploy:
  provider: heroku
  api_key:
    secure: xxx
  app: bn-dsti-devops-2020-chat
  on:
    repo: bngom/dsti-devops-2020-chat
